name: solo_social
description: SoloSocial.

version: 0.0.6

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  rxdart: ^0.23.1
  provider: ^4.0.2
  google_fonts: ^0.3.3
  firebase_auth: ^0.15.3+1
  google_sign_in: ^4.1.1
  #cloud_firestore: ^0.13.0+1
  groovin_widgets: ^1.4.2
  #auto_animated: ^2.0.1
  avataaar_image: ^1.0.8
  material_design_icons_flutter: ^3.4.4795
  introduction_screen: ^1.0.7
  shared_preferences: ^0.5.6+1
  flutter_signin_button: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
